name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GIT_SSH_COMMAND: "ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=5"

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@209.38.150.174 << 'EOF'
            cd workwise
            git pull origin main
            docker-compose up --build
            sleep 10  # Allow some time for the app to start
            curl -f http://localhost:5000/login || exit 1  # Check if the app is running
          EOF
